### ISSUE TITLE
DownloadError: ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by shadow443** [atulkadian/gdrivemirror_bot#10]
Hi, I have the following error when I try to download a YouTube video. The command used is: video | linkyoutube

> usuario@test:~/gdrivemirror_bot$ python bot.py
ADMIN_MODULE not found. (Won't effect the bot though.)
[youtube] hZ1OgQL9_Cw: Downloading webpage
[youtube] hZ1OgQL9_Cw: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
2020-03-03 16:49:25,554 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/usuario/.local/lib/python2.7/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "bot.py", line 85, in start_bot
    filename = download_video.download(url)
  File "/home/usuario/gdrivemirror_bot/modules/download_video.py", line 26, in download
    info_dict = ydl.extract_info(url, download=False)
  File "/home/usuario/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/usuario/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/usuario/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: This video is unavailable.

**Comment by Skalyx14** [comment]
I am having the same problem... :/
